// Real app data + selectors re-exported into the design-system bundle so
// previews and the Claude Design agent can feed data-driven components
// (DpaCalculator, DpaCalculatorSeoSections, FloridaCountyMap,
// MortgageRatesDashboard) the same props the site's pages build.
import type { MortgageMarketSnapshot, MetricChange } from "../../src/lib/rates";

export { FLORIDA_COUNTIES, FLORIDA_DPA_PROGRAMS } from "../../src/data/dpa";
export {
  toDpaCalculatorProgramSummaries,
  getDpaProgramCountsByCounty,
} from "../../src/lib/dpa-calculator";

const changes = (w: number | null, m: number | null, y: number | null): MetricChange[] => [
  { period: "1w", value: w, direction: w === null ? "unavailable" : w > 0 ? "up" : w < 0 ? "down" : "flat" },
  { period: "1m", value: m, direction: m === null ? "unavailable" : m > 0 ? "up" : m < 0 ? "down" : "flat" },
  { period: "1y", value: y, direction: y === null ? "unavailable" : y > 0 ? "up" : y < 0 ? "down" : "flat" },
];

// Static, realistic snapshot for previews/designs — shaped exactly like the
// live FRED-backed payload the /mortgage-rates page fetches.
export const sampleMortgageMarketSnapshot: MortgageMarketSnapshot = {
  retrievedAt: "2026-08-07T12:00:00.000Z",
  effectiveDate: "2026-08-06",
  benchmarks: [
    {
      id: "30-year-fixed",
      label: "30-Year Fixed",
      seriesId: "MORTGAGE30US",
      rate: 6.38,
      effectiveDate: "2026-08-06",
      sourceId: "freddie-mac-pmms",
      frequency: "weekly",
      geography: "United States",
      rateType: "benchmark_average",
      changes: changes(-0.03, -0.09, -0.41),
    },
    {
      id: "15-year-fixed",
      label: "15-Year Fixed",
      seriesId: "MORTGAGE15US",
      rate: 5.61,
      effectiveDate: "2026-08-06",
      sourceId: "freddie-mac-pmms",
      frequency: "weekly",
      geography: "United States",
      rateType: "benchmark_average",
      changes: changes(-0.02, -0.11, -0.38),
    },
  ],
  dailyIndices: [
    {
      id: "30-year-fixed",
      label: "30-Year Conventional",
      seriesId: "OBMMIC30YF",
      rate: 6.42,
      effectiveDate: "2026-08-06",
      sourceId: "optimal-blue-obmmi",
      frequency: "daily",
      geography: "United States",
      rateType: "rate_lock_index",
      changes: changes(-0.04, -0.08, -0.39),
    },
    {
      id: "15-year-fixed",
      label: "15-Year Conventional",
      seriesId: "OBMMIC15YF",
      rate: 5.68,
      effectiveDate: "2026-08-06",
      sourceId: "optimal-blue-obmmi",
      frequency: "daily",
      geography: "United States",
      rateType: "rate_lock_index",
      changes: changes(-0.03, -0.1, -0.35),
    },
    {
      id: "fha-30-year",
      label: "30-Year FHA",
      seriesId: "OBMMIFHA30YF",
      rate: 6.12,
      effectiveDate: "2026-08-06",
      sourceId: "optimal-blue-obmmi",
      frequency: "daily",
      geography: "United States",
      rateType: "rate_lock_index",
      changes: changes(-0.05, -0.12, -0.44),
    },
    {
      id: "va-30-year",
      label: "30-Year VA",
      seriesId: "OBMMIVA30YF",
      rate: 5.94,
      effectiveDate: "2026-08-06",
      sourceId: "optimal-blue-obmmi",
      frequency: "daily",
      geography: "United States",
      rateType: "rate_lock_index",
      changes: changes(-0.04, -0.1, -0.46),
    },
    {
      id: "jumbo-30-year",
      label: "30-Year Jumbo",
      seriesId: "OBMMIJUMBO30YF",
      rate: 6.55,
      effectiveDate: "2026-08-06",
      sourceId: "optimal-blue-obmmi",
      frequency: "daily",
      geography: "United States",
      rateType: "rate_lock_index",
      changes: changes(-0.02, -0.06, -0.3),
    },
    {
      id: "usda-30-year",
      label: "30-Year USDA",
      seriesId: "OBMMIUSDA30YF",
      rate: 6.08,
      effectiveDate: "2026-08-06",
      sourceId: "optimal-blue-obmmi",
      frequency: "daily",
      geography: "United States",
      rateType: "rate_lock_index",
      changes: changes(-0.05, -0.11, -0.42),
    },
  ],
  floridaMarket: [
    {
      id: "median-listing-price",
      label: "Florida Median Listing Price",
      seriesId: "MEDLISPRIFL",
      value: 449900,
      effectiveDate: "2026-07-01",
      sourceId: "fred-florida-housing",
      frequency: "monthly",
      geography: "Florida",
      unit: "dollars",
      changes: changes(null, -0.6, -2.2),
    },
    {
      id: "active-listing-count",
      label: "Florida Active Listings",
      seriesId: "ACTLISCOUFL",
      value: 172483,
      effectiveDate: "2026-07-01",
      sourceId: "fred-florida-housing",
      frequency: "monthly",
      geography: "Florida",
      unit: "count",
      changes: changes(null, 1.8, 9.4),
    },
    {
      id: "florida-home-price-index",
      label: "Florida Home Price Index",
      seriesId: "FLSTHPI",
      value: 391.6,
      effectiveDate: "2026-04-01",
      sourceId: "fred-florida-housing",
      frequency: "quarterly",
      geography: "Florida",
      unit: "index",
      changes: changes(null, null, 1.2),
    },
  ],
  rateTrend: {
    id: "30-year-fixed-3y",
    label: "30-Year Fixed — 3-Year Trend",
    seriesId: "MORTGAGE30US",
    sourceId: "freddie-mac-pmms",
    geography: "United States",
    rateType: "benchmark_average",
    period: "3y",
    points: [
      { date: "2023-08-03", rate: 6.9 },
      { date: "2023-10-05", rate: 7.49 },
      { date: "2023-12-07", rate: 7.03 },
      { date: "2024-02-01", rate: 6.63 },
      { date: "2024-04-04", rate: 6.82 },
      { date: "2024-06-06", rate: 6.99 },
      { date: "2024-08-01", rate: 6.73 },
      { date: "2024-10-03", rate: 6.12 },
      { date: "2024-12-05", rate: 6.69 },
      { date: "2025-02-06", rate: 6.89 },
      { date: "2025-04-03", rate: 6.64 },
      { date: "2025-06-05", rate: 6.85 },
      { date: "2025-08-07", rate: 6.63 },
      { date: "2025-10-02", rate: 6.34 },
      { date: "2025-12-04", rate: 6.28 },
      { date: "2026-02-05", rate: 6.52 },
      { date: "2026-04-02", rate: 6.47 },
      { date: "2026-06-04", rate: 6.44 },
      { date: "2026-08-06", rate: 6.38 },
    ],
  },
  marketNote: {
    headline: "Rates continue drifting lower into late summer",
    body: "The 30-year benchmark has eased roughly 40 basis points over the past year while Florida inventory keeps expanding, giving buyers more negotiating room than at any point since 2022.",
    dataPointsUsed: ["MORTGAGE30US", "MEDLISPRIFL", "ACTLISCOUFL"],
    generatedAt: "2026-08-07T12:00:00.000Z",
    model: "sample-static",
  },
  sources: [
    {
      id: "freddie-mac-pmms",
      label: "Freddie Mac Primary Mortgage Market Survey",
      sourceUrl: "https://fred.stlouisfed.org/series/MORTGAGE30US",
      updateFrequency: "weekly",
    },
    {
      id: "optimal-blue-obmmi",
      label: "Optimal Blue Mortgage Market Indices",
      sourceUrl: "https://fred.stlouisfed.org/series/OBMMIC30YF",
      updateFrequency: "daily",
    },
    {
      id: "fred-florida-housing",
      label: "FRED Florida Housing Data",
      sourceUrl: "https://fred.stlouisfed.org/series/MEDLISPRIFL",
      updateFrequency: "monthly",
    },
  ],
  disclaimer:
    "Rates shown are national benchmark averages, not offers to lend. Your rate depends on credit, loan type, down payment, and other factors. Contact a licensed loan officer for a personalized quote.",
};
